### ISSUE TITLE
Love this, but would you be open to another name?

### ISSUE THREAD

**Issue by homeslicesolutions-zz** [dknutsen/ember-needs-async#30]
I love this!  I was trying to make my own version of this called “ember-data-provider” since this pattern is a provider component.  Yours is much more robust!  My only gripe is the name “NeedsAsync”.  Can this be called something else like “RunAsync” or “RunPromise” or “PromisePerformer”?

**Comment by dknutsen** [comment]
@homeslicesolutions thanks for the feedback. I'm definitely not married to the name NeedsAsync but here's why I chose it: 

At EmberConf this year Sam Selikoff was talking about declarative data loading and how it's cool if/when a "thing" (component, etc) can declaratively state its data needs. That's a bad paraphrase but hopefully you get the idea. So that idea of a component being able to declare what data it "needs" was what drove the name choice. That and the component itself is very generic and can be used with any ember concurrency task. It's basically shorthand for "this block needs the result of an async task" which would obviously be a really unwieldy component name 😁 

IMO a good name should suggest what the thing does, and also be honest about what it does. You could probably argue needs-async isn't intuitive, but it is honest. My concern with using the words "Run" and "Perform" is that they imply that the component *does something* which is dishonest in the sense that the component doesn't execute/run/perform anything (the helpers do). The component just conditionally renders blocks. And it definitely doesn't currently support Promises (just ember concurrency tasks, could probably change the component to accept promises as well but they aren't as nice to work with).

So... maybe making the component and library name the same was a mistake, though it seemed to make sense at the time, but changing the library name at this point seems like a lot of work and I'm lazy. Changing just the component name wouldn't be quite as bad but I'd want it to be something I really felt strongly about, so at the moment I'm disinclined to change the name.

That said if you really hate the name you have a couple options. You could re-export the component as something else e.g. ` app/components/provides-async.js`:
```
export { default } from 'ember-needs-async/components/needs-async';
```

And then use it like this:
```
<ProvidesAsync @needs={{find-record "user" "1"}} as |States|>
  <States.loading>loading...</States.loading>
  <States.loaded>
    ...
  </States.loaded>
</ProvidesAsync>
```

And you could also alias the argument in the reexport too so instead of `@needs` it's `@provides` or `@taskInstance` or whatever you want. 

And of course if you were just interested in the component and not the helpers you could just copy and paste the component with whatever name you prefer. In that case it's not worth the additional npm package anyway.

Hope that all makes sense, and thanks again for the feedback.

**Comment by homeslicesolutions-zz** [comment]
@dknutsen.  Thanks for the quick response!  Also, thanks for taking your time to explain.  It makes a lot of sense.  I was also at the Ember Conf this year in Portland and I also heard the talk! 

I'll continue my argument with the name. =) My concern of the name is exactly as you said: it doesn't seem intuitive. I guess it sort of answers the question "What is it?".  The answer to it would be "It is a needs async component" which to me still doesn't "really" describe it.  However, it does tells me an important aspect of the component. It is true that the component doesn't really "DO" anything, but it is helping us organize code based on the concurrency helpers and the state of its async task.  I'll admit that my original suggestions suck, but maybe the name "async-container" may be a bit more intuitive?    It's a Async Container block that yields out the state of the given task?  I don't know just a thought

```
<AsyncContainer @task={{find-record ... }} ... />
```

Anyway, your component is awesome!  Thanks for doing it!

**Comment by dknutsen** [comment]
@homeslicesolutions Really appreciate the feedback and suggestions. I am a little uncomfortable with "Container" because that can imply more of a DOM container (and I want it to be obvious that this doesn't actually render anything in the DOM). I feel like I'm into ProvidesAsync or AsyncProvider or something, but I'll keep mulling it over.
